trigger:
 - master
pool:
  vmImage: ubuntu-latest
  container: mcr.microsoft.com/dotnet/core/sdk:3.1
steps:
- script: dotnet --version
  displayName: Check version of .NET container
- script: dotnet test
  displayName: Test .NET application
  workingDirectory: ./app.tests/
- script: dotnet run
  displayName: Run .NET application
  workingDirectory: ./app/
- script: dotnet publish --output out --configuration Release --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFIle=true
  displayName: Publish .Net application
  workingDirectory: ./app/
