pool:
  vmImage: ubuntu-latest
  container: mcr.microsoft.com/dotnet/core/sdk:3.1
steps:
- script: dotnet --version
  displayName: Check version of .NET container
- script: dotnet test
  displayName: Test .NET application
  workingdirectory: ./app.tests/
- script: dotnet run
  displayName: Run .NET application
  workingdirectory: ./app/